name: All

on: [push, pull_request, pull_request_review]

jobs:
  build-tests-windows:
    name: Build and run tests on Windows
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Pull submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: |
        choco install ninja doxygen.install
        Copy "C:\Program Files\doxygen\bin\doxygen.exe" "C:\ProgramData\Chocolatey\bin\doxygen.exe"
        Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
        refreshenv
        cmake --version
        clang --version
        echo "Installed doxygen of version $(doxygen -v)."
    - name: Create build directory
      run: mkdir build
    - name: Build (debug)
      run: |
        cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Debug ..
        cmake --build . --target ALL_BUILD --config Debug
      working-directory: build
    - name: Test (debug)
      run: |
        cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Debug ..
        cmake --build . --target csl_tests --config Debug
        Copy-Item -Path ../res -Recurse -Destination ./OUTPUT/csl_tests/Debug/ -Container
        ./OUTPUT/csl_tests/Debug/CombinedShaderLanguageParserTests.exe
      working-directory: build
    - name: Build (release)
      run: |
        cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --target ALL_BUILD --config Release
      working-directory: build
    - name: Test (release)
      run: |
        cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --target csl_tests --config Release
        Copy-Item -Path ../res -Recurse -Destination ./OUTPUT/csl_tests/Release/ -Container
        ./OUTPUT/csl_tests/Release/CombinedShaderLanguageParserTests.exe
      working-directory: build